---
abstract: 'Select a random object according to its weight.'
author:
  - 'Alan Voss <alanvoss@hotmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Statistics-WeightedSelection
requires:
  Carp: '0'
  Storable: '0'
  strict: '0'
  warnings: '0'
version: '0.002'
